"""Add country_code and state_code to projects for SpeciesNet

Revision ID: 5cac8bb39056
Revises: 761c29fe9d41
Create Date: 2025-12-29 15:08:52.694761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cac8bb39056'
down_revision: Union[str, None] = '761c29fe9d41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('country_code', sa.String(length=3), nullable=True))
    op.add_column('projects', sa.Column('state_code', sa.String(length=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'state_code')
    op.drop_column('projects', 'country_code')
    # ### end Alembic commands ###
